[package]
name = "code"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8"
num-complex = "0.4"
nalgebra = "0.34"
num-rational = "0.4"
itertools = "0.14"
rand = "0.9"
radix_trie = "0.3"
num = "0.4"

[profile.test]
opt-level=3